trigger: none 
pool: 
  name: terraform-agent

variables:
  webappName: 'webapp091'

stages:
  - stage: Build_UI_Artifacts
    displayName: Build artifact stage
    jobs:
      - job: Build_UI_Artifacts
        displayName: Build UI based artifcats for react App
        steps:
          - checkout: self
          
          - task: NodeTool@0
            displayName: Install Node Version 18.x
            inputs:
              versionSource: 'spec'
              versionSpec: '18.x'
          
          - task: Npm@1
            displayName: npm Install
            inputs:
              command: 'install'
              workingDir: '$(System.DefaultWorkingDirectory)/'
          
          - task: Npm@1
            displayName: npm run build
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)/'
              customCommand: 'build'
          
          

